logging:
  file:
    enable: true
    level: INFO
    path: logs
    rotation: "10 MB"
    retention: "7 days"
  console:
    enable: true
    level: INFO

db_meta:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123321
  database: meta

db_dw:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123321
  database: dw

qdrant:
  host: 127.0.0.1
  port: 6333
  embedding_size: 1024

embedding:
  host: 127.0.0.1
  port: 8081
  model: BAAI/bge-large-zh-v1.5


es:
  host: 127.0.0.1
  port: 9200
  index_name: data_agent


llm:
  model_name: deepseek-chat
  api_key: sk-c2c3ddb62d9d42f482c16b8e7307c308
  base_url: https://api.deepseek.com
